### PR TITLE
TR-2739 fix no MissingScopeException

### PR DESCRIPTION
**Pull request by augustas**
Removed mention of `oat\taoLti\models\classes\Security\MissingScopeException`
 
Related to : https://oat-sa.atlassian.net/browse/TR-2739
 
Testing described in companion PR
  
#### Dependencies
 
Requires :
 - [x] https://github.com/oat-sa/extension-tao-lti/pull/340
   
Companion PR :
 - [ ] https://github.com/oat-sa/tao-deliver-be/pull/708

### CODE REVIEW

**Review by poyuki — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by wazelin — CHANGES_REQUESTED** [review]
This may also not be needed after all 🤔 
See the comment on the dependency PR.

**Review by wazelin — CHANGES_REQUESTED** [review]
This PR makes sense only if the taoLti dependency is bumped in composer.json.

**Comment by augustas** [comment]
> This PR makes sense only if the taoLti dependency is bumped in composer.json.

Right, I've bumped the dependency version

**Review by wazelin — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

**Pull request merged**
