### PR TITLE
Feature/nex 248/publication service

### PR DESCRIPTION
**Pull request by boajer**
Related to: https://oat-sa.atlassian.net/browse/NEX-248

### CODE REVIEW

**Comment by boajer** [comment]
Looks ok for me

**Review by ferenckiss89 — APPROVED** [review]

**Review by julien-sebire — APPROVED** [review]
Let's go !

**Comment by boajer** [comment]
Guys, we are missing updater there and version bump in manifest.

**Comment by ferenckiss89** [comment]
> Guys, we are missing updater there and version bump in manifest.

true, I'll provide

**Pull request merged**
